buildCommand: "docker build -t n8n ."
dockerfile: |
  FROM n8nio/n8n:latest
  CMD ["--webhook-port", "5678"]
  EXPOSE 5678

dockerCompose:
  version: "3.8"
  services:
    web:
      image: n8n
      ports:
        - "5678:5678"
